export const ERROR_NO_RESOLVER = 'Domain has no resolver'
export const ERROR_NOT_ADDR = 'Domain has no addr resolver'
export const ERROR_NOT_COIN_ADDR = 'Domain has no coin addr resolver'
export const ERROR_NO_ADDR_SET = 'Domain has no address set'
export const ERROR_NO_COIN_ADDR_SET = 'Domain has no coin address set'
export const ERROR_NO_REVERSE_RECORD = 'Address has no reverse record'
